const ASSET_TYPES = {
  SOP: {name:'Standard Operating Procedure', bestFor:'Repeatable operational procedures requiring governance and compliance.', sections:['Title','Purpose','Scope','Audience','Prerequisites','Roles and Responsibilities','Tools and Materials','Procedure','Quality Checks','Warnings and Cautions','References','Version History']},
  QRG: {name:'Quick Reference Guide', bestFor:'Fast lookup at the moment of need.', sections:['Title','Audience','When to Use','Key Steps','Tips','Common Errors','References']},
  'Job Aid': {name:'Job Aid', bestFor:'On-the-job performance support for decisions or procedures.', sections:['Title','Task Overview','Audience','Before You Begin','Steps or Decision Points','Examples','Screenshots','Tips','References']},
  Checklist: {name:'Checklist', bestFor:'Verification, inspection, readiness, or completion tracking.', sections:['Title','Purpose','Audience','Checklist Items','Completion Criteria','Escalation or Exceptions','Version History']},
  'Participant Workbook': {name:'Participant Workbook', bestFor:'Instructor-led or blended learning with activities.', sections:['Title','Welcome','Learning Objectives','Agenda','Key Concepts','Activities','Practice Scenarios','Knowledge Checks','Reflection','Resources']},
  'Facilitator Guide': {name:'Facilitator Guide', bestFor:'Consistent instructor delivery.', sections:['Title','Session Overview','Audience','Learning Objectives','Materials','Timing Guide','Facilitator Notes','Activities','Debrief Questions','Assessment','Resources']},
  'eLearning Script': {name:'eLearning Script', bestFor:'Self-paced digital learning production.', sections:['Title','Course Overview','Learning Objectives','Screen-by-Screen Script','Narration','On-Screen Text','Interactions','Knowledge Checks','Accessibility Notes']},
  'Slide Deck Outline': {name:'Slide Deck Outline', bestFor:'Presentation planning and stakeholder review before deck production.', sections:['Title','Audience','Presentation Goal','Slide Outline','Speaker Notes','Activities','Visual Recommendations','References']},
  'Assessment/Quiz': {name:'Assessment/Quiz', bestFor:'Measuring knowledge, skill, or readiness.', sections:['Title','Assessment Purpose','Audience','Instructions','Questions','Answer Key','Scoring Guidance','Remediation Resources']}
};
const QUESTIONS = [
  ['use','What is the primary use?',[['perform','Help someone perform a task'],['learn','Teach concepts through training'],['verify','Verify completion or quality'],['assess','Assess knowledge'],['present','Present information']]],
  ['context','Where will it be used?',[['job','During work'],['class','In class'],['online','Self-paced online'],['audit','Review or audit']]],
  ['complexity','How complex is the content?',[['simple','Simple and brief'],['steps','Step-by-step process'],['deep','Detailed with practice'],['questions','Question-based']]],
  ['governance','Does it require controlled procedure language?',[['yes','Yes'],['no','No']]]
];
const state = {brand:{org:'', owner:'', version:'1.0', confidentiality:'Internal', logo:''}, sourceText:'', screenshots:[], type:'SOP', template:null, mapped:{}, suggestions:[], selected:null};
const $ = s => document.querySelector(s);
function save(){localStorage.setItem('lab-state', JSON.stringify(state)); renderPreview();}
function load(){try{Object.assign(state, JSON.parse(localStorage.getItem('lab-state')||'{}'));}catch{}}
function recommend(ans){ if(ans.governance==='yes') return 'SOP'; if(ans.use==='assess') return 'Assessment/Quiz'; if(ans.use==='verify'||ans.context==='audit') return 'Checklist'; if(ans.context==='class'&&ans.complexity==='deep') return 'Participant Workbook'; if(ans.context==='class') return 'Facilitator Guide'; if(ans.context==='online') return 'eLearning Script'; if(ans.use==='present') return 'Slide Deck Outline'; if(ans.complexity==='simple') return 'QRG'; return 'Job Aid';}
function parseText(text){const lines=text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean); const chunks={}; let cur='Overview'; chunks[cur]=[]; for(const l of lines){const h=l.replace(/[:#\-*]/g,'').trim(); if(l.length<70 && /^(purpose|scope|audience|steps?|procedure|materials?|tools|references|objectives|agenda|assessment|questions?|warnings?|tips|overview|summary)/i.test(h)){cur=h.replace(/\b\w/g,c=>c.toUpperCase()); chunks[cur]=[]} else chunks[cur].push(l)} return chunks;}
function mapContent(){const parsed=parseText(state.sourceText); const sections=ASSET_TYPES[state.type].sections; state.mapped={}; sections.forEach(sec=>{let hit=Object.keys(parsed).find(k=>k.toLowerCase().includes(sec.split(' ')[0].toLowerCase())); state.mapped[sec]=(hit?parsed[hit]:[]).join('\n') || starter(sec);}); save(); renderMapping();}
function starter(sec){ if(sec.includes('Procedure')||sec.includes('Steps')) return '1. Add the first learner action.\n2. Add the next learner action.\n3. Confirm the expected result.'; if(sec.includes('Objective')) return 'By the end of this asset, learners will be able to perform the target task accurately and consistently.'; if(sec.includes('Warning')) return 'Add critical cautions, compliance notes, or safety considerations.'; if(sec.includes('Screenshot')) return 'Insert relevant screenshots from the screenshot uploader.'; return `Add ${sec.toLowerCase()} content.`;}
function render(){ $('#typeList').innerHTML=Object.keys(ASSET_TYPES).map(k=>`<button class="pill ${state.type===k?'active':''}" data-type="${k}">${k}</button>`).join(''); $('#typeList').onclick=e=>{if(e.target.dataset.type){state.type=e.target.dataset.type; state.template=ASSET_TYPES[state.type]; mapContent(); render();}}; $('#questions').innerHTML=QUESTIONS.map(q=>`<label>${q[1]}<select data-q="${q[0]}">${q[2].map(o=>`<option value="${o[0]}">${o[1]}</option>`).join('')}</select></label>`).join('')+'<button id="rec">Recommend best format</button><b id="recOut"></b>'; $('#rec').onclick=()=>{const a={}; document.querySelectorAll('[data-q]').forEach(x=>a[x.dataset.q]=x.value); state.type=recommend(a); $('#recOut').textContent=` Recommended: ${state.type}`; mapContent(); render();}; renderBrand(); renderMapping(); renderPreview();}
function renderBrand(){ $('#brand').innerHTML=['org','owner','version','confidentiality'].map(k=>`<label>${k}<input value="${state.brand[k]||''}" data-brand="${k}"></label>`).join('')+'<label>Logo<input type="file" id="logo" accept="image/*"></label>'; $('#brand').oninput=e=>{if(e.target.dataset.brand){state.brand[e.target.dataset.brand]=e.target.value; save();}}; $('#logo').onchange=e=>fileData(e.target.files[0]).then(d=>{state.brand.logo=d; save();});}
function renderMapping(){ const secs=ASSET_TYPES[state.type].sections; $('#mapping').innerHTML=secs.map(s=>`<label>${s}<textarea data-sec="${s}">${state.mapped?.[s]||starter(s)}</textarea></label>`).join(''); $('#mapping').oninput=e=>{if(e.target.dataset.sec){state.mapped[e.target.dataset.sec]=e.target.value; save();}};}
function renderPreview(){ const secs=ASSET_TYPES[state.type].sections; $('#preview').innerHTML=`<article class="doc"><header><div><p>${state.brand.confidentiality||'Internal'}</p><h1>${state.mapped?.Title||ASSET_TYPES[state.type].name}</h1><h2>${state.type}</h2></div>${state.brand.logo?`<img class="logo" src="${state.brand.logo}">`:''}</header><main>${secs.filter(s=>s!=='Title').map(s=>`<section><h3>${s}</h3>${fmt(state.mapped?.[s]||starter(s))}</section>`).join('')}${state.screenshots.length?`<section><h3>Screenshots</h3><div class="shots">${state.screenshots.map(x=>`<figure><img src="${x.data}"><figcaption>${x.name}</figcaption></figure>`).join('')}</div></section>`:''}</main><footer>${state.brand.org||'Organization'} • ${state.brand.owner||'Learning & Development'} • Version ${state.brand.version||'1.0'}</footer></article>`;}
function fmt(t){return '<p>'+String(t).replace(/\n/g,'</p><p>').replace(/(\d+\. )/g,'<br>$1')+'</p>'}
async function fileData(f){return new Promise(r=>{const fr=new FileReader(); fr.onload=()=>r(fr.result); fr.readAsDataURL(f);});}
function loadScript(src, globalName){return new Promise((resolve,reject)=>{if(window[globalName]) return resolve(window[globalName]); const el=document.createElement('script'); el.src=src; el.onload=()=>resolve(window[globalName]); el.onerror=()=>reject(new Error('Unable to load '+src)); document.head.appendChild(el);});}
async function extractPdf(file){const pdfjs=await loadScript('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js','pdfjsLib'); pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js'; const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise; let text=''; for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i); const content=await page.getTextContent(); text += content.items.map(item=>item.str).join(' ')+'\n';} return text;}
async function extractDocx(file){const mammoth=await loadScript('https://cdn.jsdelivr.net/npm/mammoth@1.8.0/mammoth.browser.min.js','mammoth'); const result=await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()}); return result.value;}
async function fileText(f){ if(f.name.endsWith('.pdf')) return await extractPdf(f); if(f.name.endsWith('.docx')) return await extractDocx(f); return await f.text();}
function exportWord(){const blob=new Blob([`<html><body>${$('#preview').innerHTML}</body></html>`],{type:'application/msword'}); dl(blob,'learning-asset.doc')}
function dl(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function suggest(){ const style=['Use action verbs at the start of procedural steps.','Reduce long paragraphs into scannable bullets.','Add measurable learning objectives where missing.','Confirm terminology is consistent across sections.','Add accessibility-friendly alt text for screenshots.']; state.suggestions=style.map((s,i)=>({id:i,text:s,accepted:false})); $('#suggestions').innerHTML=state.suggestions.map(x=>`<li>${x.text} <button data-acc="${x.id}">Accept</button></li>`).join(''); $('#suggestions').onclick=e=>{if(e.target.dataset.acc){const note='\n\nStyle note: '+state.suggestions[e.target.dataset.acc].text; state.mapped['Tips']=(state.mapped['Tips']||'')+note; save(); renderMapping();}};}
function wire(){ $('#source').oninput=e=>{state.sourceText=e.target.value; save();}; $('#source').value=state.sourceText||''; $('#upload').onchange=async e=>{state.sourceText=await fileText(e.target.files[0]); $('#source').value=state.sourceText; save();}; $('#parse').onclick=mapContent; $('#shots').onchange=async e=>{for(const f of e.target.files) state.screenshots.push({name:f.name,data:await fileData(f)}); save();}; $('#pdf').onclick=()=>print(); $('#word').onclick=exportWord; $('#ai').onclick=suggest; $('#syncOut').onclick=()=>dl(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'learning-asset-google-drive-sync.json'); $('#syncIn').onchange=async e=>{Object.assign(state,JSON.parse(await e.target.files[0].text())); save(); render();}; if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js');}
load();
document.querySelector('#app').innerHTML=`<div class="shell"><aside><h1>Learning Asset Builder</h1><p>Create consistent corporate Learning Assets from pasted or uploaded source content.</p><h2>1. Select Asset</h2><div id="typeList"></div><details><summary>Need help choosing?</summary><div id="questions"></div></details><h2>2. Brand</h2><div id="brand"></div><h2>3. Source</h2><textarea id="source" placeholder="Paste source content..."></textarea><input id="upload" type="file" accept=".txt,.md,.pdf,.docx"><button id="parse">Parse and map to template</button><h2>4. Screenshots</h2><input id="shots" type="file" accept="image/*" multiple><h2>5. Sync</h2><button id="syncOut">Export Google Drive sync file</button><input id="syncIn" type="file" accept="application/json"></aside><main><section class="card"><h2>Mapped Template Editor</h2><div id="mapping"></div><button id="ai">Suggest improvements</button><ul id="suggestions"></ul></section><section class="card"><div class="bar"><h2>Human Review Preview</h2><button id="pdf">Export PDF</button><button id="word">Export Word</button></div><div id="preview"></div></section></main></div>`;
wire(); render();
